(define x '#(1 2 3))
(define y x)
(display x)
(display y)
(vector-set! x 1 '(+ 3 4))
(display x)
(display y)
(display (eval (vector-ref x 1) (k-scheme-environment)))
(display (make-vector 5))
(display (make-string 5))
